### ISSUE TITLE
`mpkg` package itself doesn't work, due to missing module `semver` (Mudlet 4.17.2)

### ISSUE THREAD

**Issue by 11BelowStudio** [ZookaOnGit/mudlet-package-repository#19]
Long story short, looks like the `mpkg` package itself currently isn't working (at least on my end) due to it requiring `semver`, which isn't part of Mudlet (as of 4.17.2). And as I have no idea where one would download `semver`, this package is currently completely unusable.

Please see the attached error message screenshot thing.
![image](https://github.com/ZookaOnGit/mudlet-package-repository/assets/60523642/f12d275b-31b6-4073-a61f-0714bf4e3b2e)

Might be worth including the `semver` package with `mpkg` itself or something like that.

**Comment by ZookaOnGit** [comment]
Thank you, fixed.  Please issue
`mpkg remove mpkg`
`lua installPackage("https://zookaongit.github.io/mudlet-package-repository/mpkg.mpackage")`
to get that latest

**Comment by 11BelowStudio** [comment]
yep, it's fixed now :)
