### ISSUE TITLE
Rename `mpkg` to `mp`?

### ISSUE THREAD

**Issue by vadi2** [ZookaOnGit/mudlet-package-repository#38]
Thoughts on renaming the alias to just `mp`? `mpkg` is a bit unwieldy to type often. 

I hope nobody uses this alias already - if we decide to go for it, would need to do some digging to ensure we don't conflict with an existing and a popular package.

**Comment by ZookaOnGit** [comment]
can we think of a nice acronym (i.e pacman, apt, luarocks)?

**Comment by vadi2** [comment]
`mdlt`? Easier to type than mpkg which mostly on the right hand.

This isn't so important, more of a QoL thing :)
